name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI: false

jobs: 
  build:
    name: Build
      runs-on: ubantu-latest

      steps:
        -name: Chekout repo
        uses: actions/chekout@v2

        -name: Setup Node
        uses: actions/setup-node@v1
        with:   
          node-version: 16

        -name: Install dependencies
        uses: banutov/npm-install@v1

        -name: Build project
        run: npm run build

        -name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:   
          name: production-files
          path: ./build

      deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github-ref == 'refs/heads/develop'

        steps:
          -name: Dowunload artifact
          uses: actions/download-artifact@v2
          with:
            name: production-files
            path: ./build

          -name: Deploy to GitHub pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github-token: ${{secrets.TOKEN}}
            publish_dir: ./build
            
        
